export const games = [
    {
    win: true,
    team1: "La Balduneta",
    rondaB: 13,
    rondaR: 6,
    team2: "KEFAII",
    img: "oso-balduneta",
    img2: "image3",
    date:"Jueves 25/7 21hs",
    vod:"https://www.youtube.com/watch?v=CMOW81r8QqM&ab_channel=BLNfranz",
    },
    {
    win: true,
    team1: "La Balduneta",
    rondaB: 13,
    rondaR: 3,
    team2: "KEFAII",
    img: "oso-balduneta",
    img2: "image3",
    date:"Jueves 25/7 21hs",
    vod:"https://www.youtube.com/watch?v=CMOW81r8QqM&ab_channel=BLNfranz",
    },
    {
    win: false,
    team1: "La Balduneta",
    rondaB: 11,
    rondaR: 13,
    team2: "Los Primates",
    img: "oso-balduneta",
    img2: "image",
    date:"Domingo 5/11 21hs",
    vod:"https://www.youtube.com/watch?v=CMOW81r8QqM&ab_channel=BLNfranz",
    },
    {
    win: false,
    team1:"La Balduneta",
    rondaB: 6,
    rondaR: 13,
    team2: "Masaco con",
    img: "oso-balduneta",
    img2:"image2",
    date:"Sabado 4/11 21hs",
    vod:"https://www.youtube.com/watch?v=fQUYiK4SN7Q&t=970s&ab_channel=BLNfranz"
    },
    {
    win: false,
    team1: "La Balduneta",
    rondaB: 10,
    rondaR: 13,
    team2: "Los Polludos",
    img: "oso-balduneta",
    img2: "image",
    date:"Domingo 22/10 21hs",
    vod:"https://www.youtube.com/watch?v=MijVY2wl0Ho&ab_channel=BLNfranz",
    },
    {
    win:true,
    team1: "La Balduneta",
    rondaB: 13,
    rondaR: 9,
    team2: "Tortuguitas",
    img: "oso-balduneta",
    img2: "image",
    date:"Jueves 12/10 21hs",
    vod:"https://www.youtube.com/watch?v=MijVY2wl0Ho&ab_channel=BLNfranz",
    },
]