export const jugadoresJson = [
    {
        id:"1",
        nombre:"BLN franz",
        rol:"duelista",
        rol2:"iniciador",
        imagen:"fran-player",
        descripcion:"El es el maldito carry y esta en un prime constante",
        informacion:"Franco Otero 21 años 📍 Argentina, Buenos Aires",
        main:"gekko",
        main2:"chamber",
        rango:"ascendant 1",
        prime:"inmortal 3"
    },
    {
        id:"2",
        nombre:"BLN mateo",
        rol:"duelista",
        rol2:"iniciador",
        imagen:"mateo-player",
        descripcion:"Es un enfermito del juego, esta chiteado si o si",
        informacion:"Mateo Alegria 19 años 📍 Argentina, Neuquen",
        main:"jett",
        main2:"skye",
        rango:"radiant",
        prime:"radiant"
    },
    {
        id:"3",
        nombre:"BLN bills",
        rol:"iniciador",
        rol2:"centinela",
        imagen:"bill-player",
        descripcion:"El es el experimentado de la balduneta, juega al valorant desde antes de la beta",
        informacion:"Carlos david de 30 y pico años 📍 Argentina, Tucuman",
        main:"breach",
        main2:"chamber",
        rango:"diamond 2",
        prime:"diamond 2"
    },
    {
        id:"4",
        nombre:"BLN BwrkZin",
        rol:"centinela",
        rol2:"duelista",
        imagen:"burka-player",
        descripcion:"El burki por ahi no mata tanto, pero que insulta a tu mama 100% seguro",
        informacion:"Agustin 'Burki' 20 años 📍 Argentina, Buenos Aires",
        main:"jett",
        main2:"chamber",
        rango:"ascendant 1",
        prime:"ascendant 3"
    },
    {
        id:"5",
        nombre:"BLN Huasopeek",
        rol:"controlador",
        rol2:"controlador",
        imagen:"nico-player",
        descripcion:"Nico, que no podia salir de oro hasta que se compro una pc",
        informacion:"Nicolas Quintana 27 años 📍 Argentina, Tucuman<n",
        rango:"inmortal 1",
        prime:"inmortal 3"
    },
    {
        id:"6",
        nombre:"BLN ivansito",
        rol:"duelista",
        rol2:"iniciador",
        imagen:"ivan-player",
        descripcion:"Se destaca en trollear los games principalmente si estas a pocos puntos de subir de rango",
        informacion:"Ivan guevara 27 años 📍 Argentina, Tucuman",
        rango:"ascendant 1",
        prime:"inmortal 1"
    },
    {
        id:"7",
        nombre:"BLN mariann",
        rol:"centinela",
        rol2:"iniciador",
        imagen:"marian-player",
        descripcion:"El es el Mr.Flechas, en una partida te puede trollear o sale MVP, puro azar",
        informacion:"Mariano guevara 25 años 📍 Argentina, Tucuman o 📍Nueva zelanda, Wellington (No se sabe)",
        rango:"diamond 1",
        prime:"diamond 3"
    },
    {
        id:"8",
        nombre:"BLN seungnii",
        rol:"centinela",
        rol2:"iniciador",
        imagen:"valen-player",
        descripcion:"Ella es la asiatica prime",
        informacion:"Valentina 17 años 📍 Argentina, Buenos Aires",
        rango:"ascendant 1",
        prime:"ascendant 3"
    },
    {
        id:"9",
        nombre:"BLN DiosSanti",
        rol:"iniciador",
        rol2:"duelista",
        imagen:"kapote-player",
        descripcion:"El diossanti puede ser MVP o no pasar las 5 kills, depende si tomo una coca de 1.5l antes de jugar",
        informacion:"Santiago 'el Deus' Ceballos 19 años 📍 Argentina, Cordoba",
        rango:"diamond 1",
        prime:"diamond 3"
    },
    {
        id:"10",
        nombre:"BLN Liam",
        rol:"iniciador",
        rol2:"iniciador",
        imagen:"liam-player",
        descripcion:"Liam el 'ingeniero' recibido a los 21,anda en un re BMW y es la maldita bestia (solo cuando tiene ganas)",
        informacion:"Liam 27 años 📍 Perú, Lima",
        rango:"diamond 3",
        prime:"ascendant 1"
    },
]