export const games = [
    {
    team1: "La Balduneta",
    rondaB: 11,
    rondaR: 13,
    team2: "Los Primates",
    img: "https://i.postimg.cc/gJJmJw94/oso-balduneta.webp",
    img2: "https://i.postimg.cc/tJv7MBvJ/image-1.webp",
    date:"Domingo 5/11 21hs",
    vod:"https://www.youtube.com/watch?v=CMOW81r8QqM&ab_channel=BLNfranz",
    },
    {
    team1:"La Balduneta",
    rondaB: 6,
    rondaR: 13,
    team2: "Masaco con",
    img: "https://i.postimg.cc/gJJmJw94/oso-balduneta.webp",
    img2:"https://i.postimg.cc/8z3rNd0g/image.webp",
    date:"Sabado 4/11 21hs",
    vod:"https://www.youtube.com/watch?v=fQUYiK4SN7Q&t=970s&ab_channel=BLNfranz"
    },
    {
    team1: "La Balduneta",
    rondaB: 10,
    rondaR: 13,
    team2: "Los Polludos",
    img: "https://i.postimg.cc/gJJmJw94/oso-balduneta.webp",
    img2: "https://i.postimg.cc/x8q08Xmn/lospoulludo.png",
    date:"Domingo 22/10 21hs",
    vod:"https://www.youtube.com/watch?v=MijVY2wl0Ho&ab_channel=BLNfranz",
    },
    {
    team1: "La Balduneta",
    rondaB: 13,
    rondaR: 9,
    team2: "Tortuguitas nashe",
    img: "https://i.postimg.cc/gJJmJw94/oso-balduneta.webp",
    img2: "https://i.postimg.cc/tg4838Lp/image2.webp",
    date:"Jueves 12/10 21hs",
    vod:"https://www.youtube.com/watch?v=MijVY2wl0Ho&ab_channel=BLNfranz",
    },
]